services:
  nginx:
    image: nginx:latest
    ports:
      - '80:80'
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./public:/usr/share/nginx/html

  node_app:
    image: node:16
    working_dir: /usr/src/app
    volumes:
      - ./app:/usr/src/app
    command: "npm start"
    ports:
      - '3000:3000'
    environment:
      NODE_ENV: production